config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :collections, only: [ :show, :new, :create, :edit, :update, :destroy ] # Collections du user
  resources :artworks, only: [ :show, :new, :create, :edit, :update, :destroy ] do
    collection do
      get :search
    end
  end # Artworks du user

  namespace :explore do # Explore all artworks from all users
    resources :artworks, only: [ :index ]
  end

  resources :users, only: [] do # View users profiles, collections or artworks
    resources :collections, only: [ :index ]
    resources :artworks, only: [ :index ]
  end

  resources :cartel_scans, only: [:create]

  # Test file, to hide later!!!
  get '/components', to: 'test#components'
  get '/autocomplete', to: 'test#autocomplete'
  resources :favorites, only: [ :index, :create, :destroy ]
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :artworks, dependent: :destroy

  validates :name, presence: true, uniqueness: { scope: :user_id }
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @number_of_collections = @user.collections.count
    @collections = @user.collections
  end

  def show
    set_collection
    @user = @collection.user
    @number_of_collections = @user.collections.count
    @artworks = @collection.artworks
  end

  def new
    @collection = Collection.new
    @user = current_user
  end

  def create
    @collection = Collection.new(collection_params)
    @collection.user = current_user
    if @collection.save
      redirect_to collection_path(@collection)
    else
      render :new
    end
  end

  def edit
    set_collection
  end

  def update
    set_collection
    @collection.update(collection_params)

    redirect_to user_collections_path(current_user)
  end

  def destroy
    set_collection
    @collection.destroy

    redirect_to user_collections_path(current_user)
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:name)
  end
end

app/controllers/explore/collections_controller.rb
class Explore::CollectionsController < ApplicationController
  def index
  end

  def show
  end
end

app/views/collections/_collection_label.html.erb
<div class="select-collection">
  <% if collection.artworks.empty? %>
    <%= image_tag "https://i.ibb.co/LrCTmMr/img-gray-square.png", alt: "alttext", class: "collection-thumbnail" %>
    <span class="body-medium"><%= collection.name %></span>
  <% else %>
    <%= cl_image_tag collection.artworks.first.photo.key, alt: "alttext", class: "collection-thumbnail" %>
    <span class="body-medium"><%= collection.name %></span>
  <% end %>
</div>

app/views/collections/create.html.erb
<h1>Collections#create</h1>
<p>Find me in app/views/collections/create.html.erb</p>

app/views/collections/destroy.html.erb
<h1>Collections#destroy</h1>
<p>Find me in app/views/collections/destroy.html.erb</p>

app/views/collections/edit.html.erb
<!-- NAVBAR -->
<div class="my-navbar bg-white">
  <div class="container navbar-container">
      <!-- Icon on the left -->
      <div class="navbar-left-side">
        <%= image_tag "icons/icon_back_arrow_black.png", class: "back-arrow" %>
      </div>

      <!-- Page Title -->
      <div class="navbar-center-element">
        <h5>Update collection</h5>
      </div>

      <!-- Icon on the right -->
<!--      <div class="navbar-right-side">
        <div class="burger icon-right" id="burger" >
        </div>
     </div> -->

      <!-- Menu overlay fullscreen -->
      <div id="myNav" class="overlay">
      <%= link_to "javascript:void(0)", class: "closebtn" do %>
        <%= image_tag "icons/icon_cross.png", class: "closebtn cross", id: "cross" %>
      <% end %>

      <div class="overlay-content">
        <h1 class="mb-3"> <%= link_to "Home", root_path %> </h1>
        <h1 class="mb-3"> <%= link_to "Explore", explore_artworks_path %> </h1>
        <h1> <%= link_to "My profile", user_collections_path(current_user) %> </h1>
        <h1> <%= link_to "Favorites", favorites_path %> </h1>
        <hr>
        <h1> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </h1>
      </div>
    </div>
  </div>
</div>


<!-- MAIN CONTENT -->
<div class="container pt-5">
  <div class="form-inputs mt-5 mb-5 ">
    <%= simple_form_for([@collection]) do |f| %>
      <%= f.input :name,
                  label:"Name",
                  placeholder: '@collection.name'%>
      <div class="mt-5 mb-5">
        <%= f.submit "Update collection", class: "button button-block" %>
      </div>
    <% end %>
  </div>

</div>

app/views/collections/index.html.erb
<%= render 'shared/navbars/navbar-heart-title-burger' %>

<%= render 'shared/profile' %>

<!-- NEW ARTWORK ICON -->
<%= link_to new_artwork_path do %>
  <%= image_tag "icons/icon_plus_black.png", alt: "alttext", class: "button-camera-main-dark" %>
<% end %>

<div class="tabs body-small max-z-index">
  <div class="tab">
    <%= link_to user_collections_path(@user) do  %>
      My collections
    <% end %>
  </div>
  <div class="tab opacity-low max-z-index">
    <%= link_to user_artworks_path(@user) do  %>
      All artworks
    <% end %>
  </div>
</div>


<div class="collection-container container d-flex flex-wrap pb-5">
  <% @collections.order("created_at desc").each do |collection| %>
    <div class="cards-triple">
      <div class="cards-triple-imgs">
        <%= link_to collection_path(collection) do %>
          <div class="img-triple">
            <% if collection.artworks[0] %>
              <div class="image img-one" style="background-image: url('<%= cl_image_path collection.artworks[0].photo.key %>');"></div>
            <% else %>
              <div class="image img-one" style="background-image: url('https://i.ibb.co/LrCTmMr/img-gray-square.png');"></div>
            <% end %>
            <% if collection.artworks[1] %>
              <div class="image img-two" style="background-image: url('<%= cl_image_path collection.artworks[1].photo.key %>');"></div>
            <% else %>
              <div class="image img-two opacity-low" style="background-image: url('https://i.ibb.co/LrCTmMr/img-gray-square.png');"></div>
            <% end %>
            <% if collection.artworks[2] %>
              <div class="image img-three" style="background-image: url('<%= cl_image_path collection.artworks[2].photo.key %>');"></div>
            <% else %>
              <div class="image img-three opacity-low" style="background-image: url('https://i.ibb.co/LrCTmMr/img-gray-square.png');"></div>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="cards-triple-infos">
        <%= link_to collection_path(collection) do %>
          <div class="single-collection-infos">
            <h4><%= collection.name %></h4>
            <p class="mid-gray body-small"><%= collection.artworks.count %> artworks</p>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/collections/new.html.erb
<div class="container">
  <div class="container-sign-in mt-5">
    <h1>Create collection</h1>
  </div>

  <div class="form-inputs mt-5 mb-5 ">	
    <%= simple_form_for([@collection]) do |f| %>
      <%= f.input :name,
                  label:"Name", 
                  placeholder: 'Add collection name'%>    
      <div class="mt-5 mb-5">
        <%= f.button :submit, "Create collection", class: "button button-block" %>
      </div>
    <% end %>
  </div>

</div>

app/views/collections/show.html.erb
<!-- NAVBAR -->
<div class="my-navbar bg-white">
  <div class="container navbar-container">
    <!-- Icon on the left -->
    <div class="navbar-left-side">
      <%= image_tag "icons/icon_back_arrow_black.png", class: "back-arrow" %>
    </div>

    <!-- Page Title -->
    <div class="navbar-center-element">
      <div class="title-username">
        <h5><%= @collection.name %> </h5>
        <h6><%= link_to user_collections_path(@collection.user) do %>
          <%= @collection.user.username %>
        <% end %></h6>
      </div>
    </div>

    <!-- Icon on the right -->
    <div class="navbar-right-side">
      <div class="burger icon-right" id="burger" >
      </div>
    </div>

    <!-- Menu overlay fullscreen -->
    <div id="myNav" class="overlay">
    <%= link_to "javascript:void(0)", class: "closebtn" do %>
      <%= image_tag "icons/icon_cross.png", class: "closebtn cross", id: "cross" %>
    <% end %>

      <div class="overlay-content">
        <h1 class="mb-3"> <%= link_to "Home", root_path %> </h1>
        <h1 class="mb-3"> <%= link_to "Explore", explore_artworks_path %> </h1>
        <h1 class="mb-3"> <%= link_to "My profile", user_collections_path(current_user) %> </h1>
        <h1> <%= link_to "Favorites", favorites_path %> </h1>
        <hr>
        <h1> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> </h1>
      </div>
    </div>
  </div>
</div>

<!-- CONTENT -->
<div class="container container-mt">
  <% if @collection.artworks.count >= 1 %>
    <% @artworks.order("created_at desc").each_slice(2) do |artwork| %>
      <div class="cards-duo">
        <div class="cards-duo-imgs">
          <div class="single-img">
            <%= link_to artwork_path(artwork[0]) do %>
              <%= cl_image_tag artwork[0].photo.key %>
            <% end %>
          </div>

          <% if artwork[1] %>
            <div class="single-img">
              <%= link_to artwork_path(artwork[1]) do %>
                <%= cl_image_tag artwork[1].photo.key %>
              <% end %>
            </div>
         <% end %>
        </div>

        <div class="cards-duo-infos">
          <div class="single-artwork-infos">
            <% if artwork[0].artist %>
              <p class="subtitle"><%= artwork[0].artist.name %></p>
            <% else %>
              <p class="subtitle">Unknown artist</p>
            <% end %>
            <h4><%= artwork[0].title.titleize %></h4>
            <p class="subtitle"><%= artwork[0].completion_year %></p>
          </div>

          <% if artwork[1] %>
            <div class="single-artwork-infos">
              <% if artwork[1].artist %>
                <p class="subtitle"><%= artwork[1].artist.name %></p>
              <% else %>
                <p class="subtitle">Unknown artist</p>
              <% end %>
              <h4><%= artwork[1].title.titleize %></h4>
              <p class="subtitle"><%= artwork[1].completion_year %></p>
            </div>
          <% end %>

        </div>
      </div>
    <% end %>
  <% else %>
    <h3 class="text-center">No artworks yet</h3>
  <% end %>

 <% if @collection.user == current_user %>
    <%= link_to edit_collection_path(@collection), class: "button mt-4" do  %>
      Edit
    <% end %>

    <%= link_to "Delete",
            collection_path(@collection), class: "button mb-5",
            method: :delete,
            data: { confirm: "Are you sure?" } %>
  <% end %>

</div>

app/views/collections/update.html.erb
<h1>Collections#update</h1>
<p>Find me in app/views/collections/update.html.erb</p>