config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :collections, only: [ :show, :new, :create, :edit, :update, :destroy ] # Collections du user
  resources :artworks, only: [ :show, :new, :create, :edit, :update, :destroy ] do
    collection do
      get :search
    end
  end # Artworks du user

  namespace :explore do # Explore all artworks from all users
    resources :artworks, only: [ :index ]
  end

  resources :users, only: [] do # View users profiles, collections or artworks
    resources :collections, only: [ :index ]
    resources :artworks, only: [ :index ]
  end

  resources :cartel_scans, only: [:create]

  # Test file, to hide later!!!
  get '/components', to: 'test#components'
  get '/autocomplete', to: 'test#autocomplete'
  resources :favorites, only: [ :index, :create, :destroy ]
end

app/views/pages/home/_homepage.html.erb
<%= render 'shared/navbars/navbar-burger-title' %>

<%= link_to new_artwork_path do %>
  <%= image_tag "icons/icon_plus_black.png", alt: "alttext", class: "button-camera-main-dark" %>
<% end %>

<!-- ARTWORK FROM ARCHIVE -->

<div class="container container-mt">
  <div class="body-large">
    <% if @artwork_archive && @artwork_archive.artist %>
      <div class="text-center">
        <% if @artwork_archive.title == "" %>
          Revisit <i>Unknown title</i> by <%= @artwork_archive.artist.name.titleize %>
        <% else %>
          Revisit <i><%= @artwork_archive.title.titleize %></i> by <%= @artwork_archive.artist.name.titleize %>
        <% end %>
      </div>

      <%= link_to artwork_path(@artwork_archive) do %>
        <div class="card-text-over-img mt-3">
          <div class="artwork-infos">
            <span class="subtitle"><%= @artwork_archive.artist.name.titleize %></span>
            <% if @artwork_archive.title == "" %>
              <h3>Unknown title</h3>
            <% else %>
              <h3><%= @artwork_archive.title.titleize %></h3>
            <% end %>
            <span class="subtitle"><%= @artwork_archive.completion_year %></span>
          </div>

          <div class="image-gradient">
          </div>

          <%= cl_image_tag @artwork_archive.photo.key  %>

          <div class="collection-tag">
            <h5><%= @artwork_archive.collection.name %></h5>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
</div>


<!-- MY COLLECTIONS SLIDER -->

<div class="my-collections">
<!--   <div class="gradient">
  </div> -->

  <div class="body-large text-center mb-1">
    My collections
  </div>

  <div class="slider">
    <div class="collection-container d-flex ml-2">
      <% @collections.order("created_at desc").each do |collection| %>
        <div class="cards-triple mr-1">
          <div class="cards-triple-imgs">
            <%= link_to collection_path(collection) do %>
              <div class="img-triple img-triple-margin">
                <% if collection.artworks[0] %>
                  <div class="image img-one" style="background-image: url('<%= cl_image_path collection.artworks[0].photo.key %>');"></div>
                <% else %>
                  <div class="image img-one" style="background-image: url('https://i.ibb.co/LrCTmMr/img-gray-square.png');"></div>
                <% end %>
                <% if collection.artworks[1] %>
                  <div class="image img-two" style="background-image: url('<%= cl_image_path collection.artworks[1].photo.key %>');"></div>
                <% else %>
                  <div class="image img-two opacity-low" style="background-image: url('https://i.ibb.co/LrCTmMr/img-gray-square.png');"></div>                <% end %>
                <% if collection.artworks[2] %>
                  <div class="image img-three" style="background-image: url('<%= cl_image_path collection.artworks[2].photo.key %>');"></div>
                <% else %>
                  <div class="image img-three opacity-low" style="background-image: url('https://i.ibb.co/LrCTmMr/img-gray-square.png');"></div>                <% end %>
              </div>
            <% end %>
          </div>

          <div class="cards-triple-infos">
            <%= link_to collection_path(collection) do %>
              <div class="single-collection-infos">
                <h4><%= collection.name %></h4>
                <p class="mid-gray body-small"><%= collection.artworks.count %> artworks</p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
 </div>
</div>


<!-- LATEST POSTS FROM THE COMMUNITY -->

<div class="container pb-5">

  <div class="body-large mb-4 text-center">
    Latest posts from the community
  </div>

  <% @artworks.first(3).each do |artwork| %>
    <div class="card-explore">
     <div class="card-explore">
      <div class="explore-top-infos">
        <div class="d-flex">
          <%= cl_image_tag artwork.user.photo.key, alt: "alttext" %>
          <%= link_to user_collections_path(artwork.user) do %>
            <h5><%= artwork.user.username %></h5>
          <% end %>
        </div>

        <% if artwork.location && artwork.location.length > 0 %>
          <div class="body-xs location">
            <p class="location-string">
              <i class="fas fa-map-marker-alt mr-1" style="font-size: 12px"></i>
              <%= artwork.location %>
            </p>
          </div>
        <% end %>
      </div>

      <%= link_to artwork_path(artwork) do %>

        <div class="card-text-over-img mt-3">
          <div class="artwork-infos">
            <% if artwork.artist %>
              <span class="subtitle"><%= artwork.artist.name.titleize %></span>
            <% else %>
              <span class="subtitle">Unknown artist</span>
            <% end %>
            <% if artwork.title == "" %>
              <h3>Unknown title</h3>
            <% else %>
              <h3><%= artwork.title.titleize %></h3>
            <% end %>
            <span class="subtitle"><%= artwork.completion_year %></span>
          </div>

          <div class="image-gradient">
          </div>

          <%= cl_image_tag artwork.photo.key  %>

          <div class="collection-tag">
            <h5><%= artwork.collection.name %></h5>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>

  <div class="text-center mb-5">
    <%= link_to "View more posts", explore_artworks_path, class: "button" %>
  </div>
</div>

app/views/pages/home/_landing.html.erb
<body class="body-landing">

  <div class="landing">

    <div class="container">

      <h1>Curators</h1>

      <div class="mt-3">
        <p class="body-medium">Share and discover artworks with Curators, the social network for art enthusiasts.</p>
      </div>

      <%= link_to "Log in", new_user_session_path, class: "button button-stroke-white mt-3" %>
      <p class="body-small mt-4"> No account yet? <%= link_to "Sign up", new_user_registration_path, class: "underline" %> </p>
    </div>
  </div>

</body>